apiVersion: v1
appVersion: "4.1.0"
description: A Helm chart for the GitPrime application stack
name: gitprime-app
version: 4.1.0
icon: https://s3-us-west-2.amazonaws.com/gitprime-email-images/gitprime-logo-icon.png
