image:
environment: "ci"
postgresql:
  fullNameOverride: "flow-tickets-delivery-ci-postgresql"
  persistence:
    enabled: false
  pgHbaConfiguration: |-
    local all all trust
    host all all localhost trust
    host all all 10.0.0.0/8 trust
  initdbScripts:
    00_fundamentals_db.sql: |
      CREATE USER flow_tickets_delivery_superuser WITH SUPERUSER;
      CREATE USER flow_tickets_delivery_user WITH CREATEDB;
      CREATE USER flow_tickets_delivery_user WITH CREATEDB;
      CREATE USER flow_tickets_delivery_migration_user WITH CREATEDB;
      CREATE DATABASE flow_tickets_delivery;
      GRANT ALL PRIVILEGES ON DATABASE flow_tickets_delivery TO flow_tickets_delivery_user;
      GRANT ALL PRIVILEGES ON DATABASE flow_tickets_delivery TO flow_tickets_delivery_migration_user;
    01_create_extension.sh: |
      #!/bin/bash
      psql -U flow_tickets_delivery_superuser -d flow_tickets_delivery -c "CREATE EXTENSION IF NOT EXISTS ltree;" -c "\q"
service:
  type: NodePort
  port: 80
frontend:
  image:
    repository: "gp-docker.gitprime-ops.com/dev/flow-tickets-delivery-frontend"
    tag: "latest"
  env:
    REACT_APP_FLOW_TICKETS_DELIVERY_API_URL: http://localhost:8100/api/code
backend:
  env:
    FLOW_TICKETS_DELIVERY_DEVELOP: "false"
    FLOW_TICKETS_DELIVERY_DEBUG: "true"
    FLOW_TICKETS_DELIVERY_GUNICORN_LOG_LEVEL: "INFO"
    FLOW_TICKETS_DELIVERY_CORS_ORIGIN_HEADER: "https://sandbox-01.gitprime-ops.com"
    FLOW_TICKETS_DELIVERY_MIGRATION_USER: "flow_tickets_delivery_migration_user"
  image:
    repository: "gp-docker.gitprime-ops.com/dev/flow-tickets-delivery-backend"
    tag: "latest"
