apiVersion: v2
name: flow-fundamentals
description: Bounded Context for Fundamental Report and Friends
type: application
version: 0.2.1
appVersion: 0.1.0
dependencies:
- name: postgresql
  version: 8.3.3
  repository: https://kubernetes-charts.storage.googleapis.com/
