apiVersion: v1
appVersion: "0.0.2"
description: A Helm chart for the GitPrime Reporting Pipeline
name: gp-reporting-pipeline
version: 0.0.1
icon: https://s3-us-west-2.amazonaws.com/gitprime-email-images/gitprime-logo-icon.png
