global:
  environment:
    parentName: sandbox
    modifierValue: ""
  build:
    commitSHA: "latest"
  datadog:
    enabled: true
  dns:
    ndots: 2
  volumes:
    enableLocalMount: false
    nodeMountDirectory: /mnt/working-storage
    podMountDirectory: /var/working-storage

gp-reporting-sink:
  enabled: true
gp-reporting-kafka-health:
  enabled: true

