# Environment values
environment:
  parentName: sandbox
  modifierValue: ""

kafkaConnect:
  host: localhost
  port: 8083
  nodePort: 31083
  targetPort: 8083

# Values for cp-helm-charts to deploy Kafka and kafka-connect
cp-helm-charts:
  cp-kafka:
    brokers: 2
    configurationOverrides:
      offsets.topic.replication.factor: "2"
    nodeport:
      enabled: true
      firstListenerPort: 31090
  cp-kafka-rest:
    external.enabled: true
  cp-kafka-connect:
    configurationOverrides:
      "key.converter": "org.apache.kafka.connect.json.JsonConverter"
      "value.converter": "org.apache.kafka.connect.json.JsonConverter"
      "config.storage.replication.factor": "2"
      "offset.storage.replication.factor": "2"
      "status.storage.replication.factor": "2"

# Control whether other cp-helm-charts are part of this deployment.
# See https://github.com/confluentinc/cp-helm-charts/issues/224 for discussion about why
# these are at the root level and not parented by cp-helm-charts
cp-schema-registry:
  enabled: true
cp-kafka-rest:
  enabled: true
cp-ksql-server:
  enabled: false
cp-control-center:
  enabled: false
