# Environment values
environment:
  parentName: sandbox
  modifierValue: ""

# Values for cp-helm-charts to deploy Kafka and kafka-connect
cp-helm-charts:
  cp-kafka:
    brokers: 1
    configurationOverrides:
      offsets.topic.replication.factor: "1"
      "advertised.listeners": |-
        EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
    persistence:
      enabled: true
      size: 1Gi
    nodeport:
      enabled: true
    prometheus:
      jmx:
        enabled: false
    cp-zookeeper:
      servers: 1
      persistence:
        enabled: true
        dataDirSize: 1Gi
        dataLogDirSize: 2Gi
      prometheus:
        jmx:
          enabled: false
  cp-kafka-connect:
    configurationOverrides:
      config.storage.replication.factor: "1"
      offset.storage.replication.factor: "1"
      status.storage.replication.factor: "1"
      value.converter: org.apache.kafka.connect.json.JsonConverter
    prometheus:
      jmx:
        enabled: false

# Suppress sub-charts of cp-helm-charts that we don't want.
# See https://github.com/confluentinc/cp-helm-charts/issues/224 for discussion about why
# these are at the root level and not parented by cp-helm-charts
cp-schema-registry:
  enabled: false
cp-kafka-rest:
  enabled: false
cp-ksql-server:
  enabled: false
cp-control-center:
  enabled: false
