{{- $templateData := dict "operationMode" "new-repo-worker" }}
{{- $_ := set $templateData "replicaCount" .Values.dataPipeline.newRepoWorker.replicaCount }}
{{- $_ := set $templateData "environment" .Values.dataPipeline.newRepoWorker.environment }}
{{- $_ := set $templateData "javaOptions" .Values.dataPipeline.newRepoWorker.javaOptions }}
{{- $_ := set $templateData "newListeners" .Values.dataPipeline.newRepoWorker.newListeners }}
{{- $_ := set $templateData "newThreadsPerListener" .Values.dataPipeline.newRepoWorker.newThreadsPerListener }}
{{- $_ := set $templateData "newMaxCommitCount" .Values.dataPipeline.newRepoWorker.newMaxCommitCount }}
{{- $_ := set $templateData "processorThreadCount" .Values.dataPipeline.newRepoWorker.processorThreadCount }}
{{- $_ := set $templateData "maxConcurrentJobs" .Values.dataPipeline.newRepoWorker.maxConcurrentJobs }}
{{- $_ := set $templateData "maxCommitCount" .Values.dataPipeline.newRepoWorker.maxCommitCount }}
{{- $_ := set $templateData "resources" .Values.dataPipeline.newRepoWorker.resources }}
{{- $_ := set $templateData "logLevel" .Values.dataPipeline.newRepoWorker.logLevel }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
