# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

build:
  commitSHA: "latest"

datadog:
  enabled: false

dns:
  ndots: 2

volumes:
  enableLocalMount: false
  nodeMountDirectory: /mnt/working-storage
  podMountDirectory: /var/working-storage

application:
  replicaCount: 1
  javaOptions: ""
  webPort: "8080"
  nodePort: "30680"
  activeProfiles: "org-virtualteam-sink,ticket-sink,user-changed-sink,alias-sink,project-sink,pr-event-sink,pr-comment-sink,team-sink,organization-sink,member-sink,apex-sink,vendor-sink,work-event-sink,pull-request-sink,commit-event-sink,ticket,event-sink,ticket-comment-sink,group-sink,org-reportpreferences-sink,materialized-view-rights-sink"
