reportingshell:
  deployEnabled: true
  dockerImage: "gp-docker.gitprime-ops.com/cloud/gitprime-reporting-shell"
  replicaCount: 1
  logLevel: "INFO"
  javaOptions: "-d64 -Xms2g -Xmx4g"
  resources:
    requests:
      cpu: "100m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"

