{{- $templateData := dict "operationMode" "apexUserChangedEvent" }}
{{- $_ := set $templateData "commitSHA" .Values.global.build.commitSHA }}
{{- $_ := set $templateData "environment" .Values.global.environment }}
{{- $_ := set $templateData "dockerImage" .Values.datasink.dockerImage }}
{{- $_ := set $templateData "deployEnabled" .Values.datasink.apexUserChangedEvent.deployEnabled }}
{{- $_ := set $templateData "activeProfiles" .Values.datasink.apexUserChangedEvent.activeProfiles }}
{{- $_ := set $templateData "replicaCount" .Values.datasink.apexUserChangedEvent.replicaCount }}
{{- $_ := set $templateData "javaOptions" .Values.datasink.apexUserChangedEvent.javaOptions }}
{{- $_ := set $templateData "resources" .Values.datasink.apexUserChangedEvent.resources }}
{{- $_ := set $templateData "logLevel" .Values.datasink.apexUserChangedEvent.logLevel }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "datasink.deploymentTemplate" $templateData }}
