{{- $templateData := dict "operationMode" "materializationEventsMemberApexUserVisibility" }}
{{- $_ := set $templateData "commitSHA" .Values.global.build.commitSHA }}
{{- $_ := set $templateData "environment" .Values.global.environment }}
{{- $_ := set $templateData "dockerImage" .Values.datasink.dockerImage }}
{{- $_ := set $templateData "deployEnabled" .Values.datasink.materializationEventsMemberApexUserVisibility.deployEnabled }}
{{- $_ := set $templateData "activeProfiles" .Values.datasink.materializationEventsMemberApexUserVisibility.activeProfiles }}
{{- $_ := set $templateData "replicaCount" .Values.datasink.materializationEventsMemberApexUserVisibility.replicaCount }}
{{- $_ := set $templateData "javaOptions" .Values.datasink.materializationEventsMemberApexUserVisibility.javaOptions }}
{{- $_ := set $templateData "resources" .Values.datasink.materializationEventsMemberApexUserVisibility.resources }}
{{- $_ := set $templateData "logLevel" .Values.datasink.materializationEventsMemberApexUserVisibility.logLevel }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "datasink.deploymentTemplate" $templateData }}
