{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "proficiency-report.serviceAccountName" . }}
  labels:
{{ include "proficiency-report.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: proficiency-report
  name: spark-controller-submit
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spark-controller-submit-binding
  namespace: proficiency-report
subjects:
- kind: ServiceAccount
  name: {{ include "proficiency-report.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: spark-controller-submit
  apiGroup: ""
{{- end }}
