# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

dataPipeline:
  build:
    commitSHA: ""

  environment:
    - name: GP_AOD_QUEUE_NAME
      value: "java-aod-repo-process-request"

  datadog:
    enabled: false

  dns:
    ndots: 2

  volumes:
    enableLocalMount: false
    nodeMountDirectory: /mnt/repo-storage
    podMountDirectory: /var/repos

  newRepoWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    newThreadsPerListener: 1
    newMaxCommitCount: 600
    newListeners: 2
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  incrementalRepoWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    incrThreadsPerListener: 1
    incrMaxCommitCount: 600
    incrListeners: 2
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  aodWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    aodThreadsPerListener: 1
    aodMaxCommitCount: 600
    aodListeners: 2
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  ticketWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    ticketThreadsPerListener: 1
    ticketListeners: 1
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 1
      - name: GP_TICKET_WEBHOOK_WORKERS_PER_LISTENER
        value: 1
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_MAX_CONCURRENT_PROJECTS_PER_ORG
        value: 40
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  prWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    prThreadsPerListener: 1
    prListeners: 1
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 1
      - name: GP_PR_WEBHOOK_WORKERS_PER_LISTENER
        value: 1
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_MAX_CONCURRENT_PROJECTS_PER_ORG
        value: 40
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  reprocessWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    reprocessThreadsPerListener: 1
    reprocessListeners: 1
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 1
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi


  batchWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    logLevel: INFO
    environment:
      - name: GP_BATCH_PROCESSING
        value: 1
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  scheduleWorker:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    maxConcurrentJobs: 1
    maxCommitCount: 600
    processorThreadCount: 2
    logLevel: INFO
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 1
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_SCHEDULED_TASK_SET
        value: cluster_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi

  utility:
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    logLevel: DEBUG
    environment:
      - name: GP_REPROCESS_LISTENERS
        value: 0
      - name: GP_REPO_DELETE_LISTENERS
        value: 0
      - name: GP_AOD_LISTENERS
        value: 0
      - name: GP_AOD_WORKERS_PER_LISTENER
        value: 0
      - name: GP_NEW_LISTENERS
        value: 0
      - name: GP_NEW_WORKERS_PER_LISTENER
        value: 0
      - name: GP_INCREMENTAL_LISTENERS
        value: 0
      - name: GP_INCREMENTAL_WORKERS_PER_LISTENER
        value: 0
      - name: GP_TICKET_LISTENERS
        value: 0
      - name: GP_TICKET_WORKERS_PER_LISTENER
        value: 0
      - name: GP_TICKET_WEBHOOK_LISTENERS
        value: 0
      - name: GP_TICKET_WEBHOOK_WORKERS_PER_LISTENER
        value: 0
      - name: GP_PR_LISTENERS
        value: 0
      - name: GP_PR_WORKERS_PER_LISTENER
        value: 0
      - name: GP_PR_WEBHOOK_LISTENERS
        value: 0
      - name: GP_MAX_REPO_PROCESSING_SECONDS
        value: 2700
      - name: GP_SCHEDULED_TASK_SET
        value: local_tasks
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi
