apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-master-svc
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.service.clusterPort }}
    targetPort: cluster
    name: cluster
  - port: {{ .Values.service.webPort }}
    targetPort: http
    name: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-web-nodeport
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
spec:
  type: NodePort
  ports:
    - name: {{ include "spark.fullname" . }}-web-nodeport
      port: {{ .Values.master.webPort }}
      nodePort: {{ .Values.master.web.nodePort }}
      targetPort: {{ .Values.master.master.webPort }}
  selector:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-cluster-nodeport
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: master
spec:
  type: NodePort
  ports:
    - name: {{ include "spark.fullname" . }}-cluster-nodeport
      port: {{ .Values.master.clusterPort }}
      nodePort: {{ .Values.master.cluster.nodePort }}
      targetPort: {{ .Values.master.cluster.clusterPort }}
  selector:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master
