{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gp-pyspark.serviceAccountName" . }}
  labels:
{{ include "gp-pyspark.labels" . | nindent 4 }}
---
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: null
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: spark-controller-submit
    namespace: gp-pyspark
  rules:
  - apiGroups:
    - ""
    - extensions
    - apps
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
    - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spark-controller-submit-binding
  namespace: gp-pyspark
subjects:
- kind: ServiceAccount
  name: {{ include "gp-pyspark.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: spark-controller-submit
  apiGroup: ""
{{- end }}
