# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

reportingPipeline:
  build:
    commitSHA: "7bdf42a09f518eaa419b227c4a449a662eb38dc1"

  datadog:
    enabled: false

  dns:
    ndots: 2

  volumes:
    enableLocalMount: false
    nodeMountDirectory: /mnt/repo-storage
    podMountDirectory: /var/repos

  etlService:
    replicaCount: 1
    javaOptions: ""
