# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

reportingPipeline:
  build:
    commitSHA: "latest"

  datadog:
    enabled: false

  dns:
    ndots: 2

  volumes:
    enableLocalMount: false
    nodeMountDirectory: /mnt/repo-storage
    podMountDirectory: /var/repos

  reportingService:
    replicaCount: 1
    javaOptions: ""
    webPort: "8080"
    nodePort: "33080"
