---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gp-pyspark
  namespace: gp-pyspark
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: gp-pyspark
  chart:
    git: git@github.com:Git-Prime/gphelm-chart-repo.git
    path: charts/gp-pyspark/v0.0.1/
    version: 0.0.1
    ref: INFRA-915/add_pyspark_chart
  values:
    image:
      tag: a665c4da4dce2feec4ccc4e28226a32617867b45
    suspend: false
