datasink:
  dockerImage: "gp-docker.gitprime-ops.com/cloud/gitprime-reporting-sink"

  workevents:
    deployEnabled: true
    activeProfiles: "commit-work-event-sink,pull-request-comment-work-event-sink,pull-request-event-work-event-sink,pull-request-work-event-sink,ticket-comment-work-event-sink,ticket-event-work-event-sink,ticket-work-event-sink"
    replicaCount: 1
    logLevel: "INFO"
    javaOptions: "-d64 -Xms2g -Xmx4g"
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"

  factdata:
    deployEnabled: true
    activeProfiles: "json,alias-sink,apex-sink,apex-user-group-sink,group-sink,member-role-view-rights-sink,member-sink,org-reportpreferences-sink,org-virtualteam-sink,organization-sink,project-sink,team-membership-sink,team-sink,vendor-sink"
    replicaCount: 1
    logLevel: "INFO"
    javaOptions: "-d64 -Xms2g -Xmx4g"
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"

  materializationEventsMemberApexUserVisibility:
    deployEnabled: true
    activeProfiles: "materialized-view-rights-sink"
    logLevel: "INFO"
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"

  materializationEventsApexUserTeamAffiliation:
    deployEnabled: true
    activeProfiles: "apex-user-team-affiliation-changed-sink"
    logLevel: "INFO"
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"

  apexUserChangedEvent:
    deployEnabled: true
    activeProfiles: "user-changed-sink"
    logLevel: "INFO"
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"

  viewRightsChangedEvent:
    deployEnabled: true
    activeProfiles: "member-rights-changed-sink"
    logLevel: "INFO"
    replicaCount: 1
    javaOptions: "-d64 -Xms2g -Xmx4g"
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"