{{- $templateData := dict "operationMode" "schedule-worker" }}
{{- $_ := set $templateData "replicaCount" .Values.dataPipeline.scheduleWorker.replicaCount }}
{{- $_ := set $templateData "environment" .Values.dataPipeline.scheduleWorker.environment }}
{{- $_ := set $templateData "javaOptions" .Values.dataPipeline.scheduleWorker.javaOptions }}
{{- $_ := set $templateData "processorThreadCount" .Values.dataPipeline.scheduleWorker.processorThreadCount }}
{{- $_ := set $templateData "maxConcurrentJobs" .Values.dataPipeline.scheduleWorker.maxConcurrentJobs }}
{{- $_ := set $templateData "maxCommitCount" .Values.dataPipeline.scheduleWorker.maxCommitCount }}
{{- $_ := set $templateData "resources" .Values.dataPipeline.scheduleWorker.resources }}
{{- $_ := set $templateData "logLevel" .Values.dataPipeline.scheduleWorker.logLevel }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
