{{- $templateData := dict "operationMode" "utility" }}
{{- $_ := set $templateData "replicaCount" .Values.dataPipeline.utility.replicaCount }}
{{- $_ := set $templateData "environment" .Values.dataPipeline.utility.environment }}
{{- $_ := set $templateData "javaOptions" .Values.dataPipeline.utility.javaOptions }}
{{- $_ := set $templateData "logLevel" .Values.dataPipeline.utility.logLevel }}
{{- $_ := set $templateData "resources" .Values.dataPipeline.utility.resources }}
{{- $templateData := dict "Values" .Values "templateData" $templateData }}
{{- include "dataPipeline.deploymentTemplate" $templateData }}
