apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "flow-fundamentals.fullname" . }}
  labels:
    {{- include "flow-fundamentals.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "flow-fundamentals.fullname" . }}-migration
    spec:
      restartPolicy: Never
      containers:
      - name: backend-migration-job-{{ .Values.backend.image.tag }}
        image: "{{ .Values.image.repository_base_url }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        env:
          - name: FLOW_FUNDAMENTALS_DEBUG
            value: "false"
          - name: FLOW_FUNDAMENTALS_ALLOWED_CIDR_NETS
            value: "10.0.0.0/8,172.32.0.0/16"
          - name: FLOW_FUNDAMENTALS_ALLOWED_HOSTS
            value: "localhost,flow-fundamentals-test,test-flow-fundamentals.gitprime-ops.com"
          - name: FLOW_FUNDAMENTALS_SECRET_KEY
            value: "somebullshitsecretkeythatshouldbechanged"
          - name: FLOW_FUNDAMENTALS_DEFAULT_DATABASE
            value: "postgresql://postgres@flow-fundamentals-test-postgresql:5432/flow_fundamentals?application_name=ff_default"
          - name: FLOW_FUNDAMENTALS_CORS_ORIGIN_HEADER
            value: "http://flow-fundamentals-frontend"
          - name: FLOW_FUNDAMENTALS_DEFAULT_ORG_NAME
            value: "GitPrime"
        args: ["python","manage.py","migrate"]
