{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flow-fundamentals.serviceAccountName" . }}
  labels:
{{ include "flow-fundamentals.labels" . | nindent 4 }}
{{- end -}}
