{{- if .Values.zookeeper.nodeport.enabled }}
  {{- $fullName := include "cp-zookeeper.fullname" . }}
  {{- $servers := cp-kafka.cp-zookeeper.servers | int }}
  {{- $clientPort := cp-kafka.cp-zookeeper.clientPort }}
  {{- $root := . }}
  {{- range $i, $e := until $servers }}
  {{- $externalListenerPort := add $root.Values.zookeeper.nodeport.firstClientPort $i }}
  {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-zookeeper.fullname" $root }}-{{ $i }}-nodeport
  labels:
    app: {{ include "cp-zookeeper.name" $root }}
    chart: {{ template "cp-zookeeper.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
    pod: {{ $responsiblePod }}
spec:
  type: NodePort
  ports:
    - name: external-zookeeper
      port: {{ $clientPort }}
      targetPort: {{ $externalListenerPort }}
      nodePort: {{ $externalListenerPort }}
      protocol: TCP
  selector:
    app: {{ include "cp-zookeeper.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
  {{- end }}

