# We'll start with values for the environment we'll be living in
environment:
  parentName: sandbox
  modifierValue: ""

build:
  commitSHA: "latest"

datadog:
  enabled: false

dns:
  ndots: 2

application:
  replicaCount: 1
  javaOptions: ""
  webPort: "8080"
  nodePort: "30780"
