apiVersion: v1
kind: Service
metadata:
  name: {{ include "flow-tickets-delivery.fullname" . }}
  labels:
    {{- include "flow-tickets-delivery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    {{- include "flow-tickets-delivery.selectorLabels" . | nindent 4 }}
